version: "3.8"

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - main
    restart: "unless-stopped"

  ui-web:
    container_name: ui-web
    build:
      context: ./ui-web
      dockerfile: Dockerfile.dev
    volumes:
      - ./ui-web:/app
      - /app/node_modules
    ports:
      - "4000:4000"
      - "9230:9229"
    networks:
      - main
    restart: "unless-stopped"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - ui-web
    networks:
      - main

networks:
  main:
    driver: bridge
