version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
      - '9229:9229'
    networks:
      - backend
    restart: 'unless-stopped'

networks:
  backend:
    driver: bridge
